# Buffer msg for GripMap
# ======================================================
# ******************************************************
# ======================================================

# Start of msg def
builtin_interfaces/Time stamp

# ======================================================
# signals
float32 tire_temp_fl
float32 tire_temp_fr
float32 tire_temp_rl
float32 tire_temp_rr
float32 x
float32 y
float32 d_local
float32 s_global_cl
float32 d_global_cl
float32 s_global_rl
float32 d_global_rl
float32 s_idx
float32 d_idx
float32 s_modulo
float32 d_modulo
float32 ax_actual
float32 ay_actual
float32 vx_actual
float32 vy_actual
float32 ax_target
float32 ay_target
float32 ax_target_mpc
float32 ay_target_mpc
float32 v_target
float32 tire_util_target
float32 ax_target_raceline
float32 ay_target_raceline
float32 v_target_raceline
float32 tire_util_target_raceline
bool on_track_bool
float32 steering_angle
float32 side_slip_angle
float32 slip_angle_fl
float32 slip_angle_fl_calc
float32 slip_angle_fr
float32 slip_angle_fr_calc
float32 slip_angle_rl
float32 slip_angle_rl_calc
float32 slip_angle_rr
float32 slip_angle_rr_calc
float32 slip_fl
float32 slip_fl_calc
float32 slip_fr
float32 slip_fr_calc
float32 slip_rl
float32 slip_rl_calc
float32 slip_rr
float32 slip_rr_calc



